"use client";
import Image from "next/image";
import { Menu, X } from "lucide-react";
import { useEffect, useState } from "react";
const enNav=[["What We Do","/what-we-do"],["MachineDNA","/machinedna"],["Equipment","/equipment"],["Service & Support","/service-support"],["Manufacturers & OEM","/manufacturers-oem"],["Partners","/distributors-partners"],["About","/about"]];
const deNav=[["Was wir tun","/de/was-wir-tun"],["MachineDNA","/de/machinedna"],["Geräte","/de/geraete"],["Service & Support","/de/service-support"],["Hersteller & OEM","/de/hersteller-oem"],["Partner","/de/vertriebspartner"],["Über uns","/de/ueber-uns"]];
const enToDe:Record<string,string>={"/":"/de","/what-we-do":"/de/was-wir-tun","/machinedna":"/de/machinedna","/equipment":"/de/geraete","/service-support":"/de/service-support","/manufacturers-oem":"/de/hersteller-oem","/distributors-partners":"/de/vertriebspartner","/about":"/de/ueber-uns","/contact":"/de/kontakt","/legal":"/de/rechtliches"};
const deToEn=Object.fromEntries(Object.entries(enToDe).map(([en,de])=>[de,en]));
function useLanguage(){const [path,setPath]=useState("/");useEffect(()=>{const currentPath=window.location.pathname.replace(/\/$/,"")||"/";setPath(currentPath);document.documentElement.lang=currentPath==="/de"||currentPath.startsWith("/de/")?"de":"en";},[]);const de=path==="/de"||path.startsWith("/de/");return {de,switchHref:de?(deToEn[path]||"/"):(enToDe[path]||"/de")};}
export function Header(){const [open,setOpen]=useState(false);const {de,switchHref}=useLanguage();const nav=de?deNav:enNav;return <header className="site-header"><div className="shell nav-wrap"><a className="brand" href={de?"/de":"/"} aria-label={de?"L4Gym Startseite":"L4Gym home"}><Image src="/l4gym-logo-dark.webp" alt="L4Gym" width={246} height={82} priority/></a><nav className={open?"nav open":"nav"} aria-label={de?"Hauptnavigation":"Main navigation"}>{nav.map(([l,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{l}</a>)}<a className="nav-contact" href={de?"/de/kontakt":"/contact"} onClick={()=>setOpen(false)}>{de?"Kontakt":"Contact"}</a><a className="language-toggle" href={switchHref} lang={de?"en":"de"} onClick={()=>setOpen(false)}>{de?"EN":"DE"}</a></nav><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={de?"Navigation umschalten":"Toggle navigation"}>{open?<X/>:<Menu/>}</button></div></header>}
export function Footer(){const {de,switchHref}=useLanguage();return <><section className="contact-band"><div className="shell contact-band-inner"><div><p className="eyebrow">{de?"Gespräch beginnen":"Start a conversation"}</p><h2>{de?"Wir entwickeln die nächste Ebene der Infrastruktur für die kommerzielle Fitnessbranche.":"Building the next layer of commercial fitness infrastructure."}</h2></div><a className="button light" href="mailto:jamie@l4gym.com">jamie@l4gym.com</a></div></section><footer><div className="shell footer-grid"><div><Image src="/l4gym-logo-dark.webp" alt="L4Gym" width={210} height={70}/><p>{de?"Vernetzte Geräte. Klarere Abläufe. Besseres Lebenszyklusmanagement.":"Connected equipment. Clearer operations. Better lifecycle management."}</p></div><div><b>{de?"Entdecken":"Explore"}</b><a href={de?"/de/was-wir-tun":"/what-we-do"}>{de?"Was wir tun":"What We Do"}</a><a href={de?"/de/machinedna":"/machinedna"}>MachineDNA</a><a href={de?"/de/geraete":"/equipment"}>{de?"Geräte":"Equipment"}</a><a href={de?"/de/service-support":"/service-support"}>Service & Support</a></div><div><b>{de?"Zusammenarbeiten":"Work with us"}</b><a href={de?"/de/hersteller-oem":"/manufacturers-oem"}>{de?"Hersteller & OEM":"Manufacturers & OEM"}</a><a href={de?"/de/vertriebspartner":"/distributors-partners"}>{de?"Vertrieb & Partner":"Distributors & Partners"}</a><a href={de?"/de/kontakt":"/contact"}>{de?"Kontakt":"Contact"}</a><a href={de?"/de/rechtliches":"/legal"}>{de?"Rechtliches":"Legal"}</a><a href={switchHref} lang={de?"en":"de"}>{de?"English":"Deutsch"}</a></div><div><b>{de?"Kontakt":"Contact"}</b><span>Jamie Bevan, {de?"Gründer":"Founder"}</span><a href="mailto:jamie@l4gym.com">jamie@l4gym.com</a><a href="https://www.l4gym.com">www.l4gym.com</a></div></div><div className="shell footnote"><span>© 2026 Jamie Bevan. L4Gym. All rights reserved.</span><span>{de?"Kommerzielle Fitnessgeräte & Industrietechnologie":"Commercial fitness equipment & industrial technology"}</span></div></footer></>}
