import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Impressum",
  description: "Anbieter-, Kontakt- und Urheberrechtsangaben für L4Gym.",
};

export default function Page() {
  return <><section className="page-hero"><div className="shell"><div><p className="eyebrow">Impressum</p><h1>Angaben zum Websiteanbieter.</h1></div><p>Informationen für dieses aus Deutschland betriebene kommerzielle Projekt.</p></div></section><section className="page-body"><div className="shell page-grid"><div><span className="number-tag">L4GYM / IMPRESSUM</span><h2>Jamie Bevan<br/>L4Gym</h2></div><div className="prose"><h2>Angaben gemäß § 5 DDG</h2><p>Jamie Bevan<br/>L4Gym — Software- und Technologieprojekt für die kommerzielle Fitnessbranche<br/>Neue Straße 15<br/>30926 Seelze<br/>Deutschland</p><h2>Kontakt</h2><p>E-Mail: <a href="mailto:jamie@l4gym.com">jamie@l4gym.com</a><br/>Website: <a href="https://www.l4gym.com">www.l4gym.com</a></p><p>Auf dieser Website wird keine private Telefonnummer veröffentlicht.</p><h2>Unternehmensstatus</h2><p>L4Gym ist derzeit ein von Jamie Bevan entwickeltes und betriebenes Software- und Technologieprojekt für die kommerzielle Fitnessbranche. L4Gym wird auf dieser Website nicht als GmbH, Ltd, ehf oder sonstige eingetragene Gesellschaft bezeichnet.</p><h2>Verantwortlich für den Inhalt</h2><p>Jamie Bevan<br/>Neue Straße 15<br/>30926 Seelze<br/>Deutschland</p><h2>Urheberrecht</h2><p><strong>Copyright © 2026 Jamie Bevan. Alle Rechte vorbehalten.</strong></p><p>Die L4Gym Software, eigene Websiteinhalte, Dokumentationen, Grafiken, Benutzeroberflächen und damit verbundene geschützte Materialien unterliegen den anwendbaren Gesetzen zum Schutz geistigen Eigentums. Sie dürfen ohne vorherige schriftliche Genehmigung nicht kopiert, vervielfältigt, verbreitet, verändert oder kommerziell verwertet werden, soweit dies nicht gesetzlich oder durch einschlägige Lizenzen Dritter gestattet ist.</p><p>Software, Bibliotheken, Marken, Bilder, Schriftarten und sonstige Materialien Dritter bleiben Eigentum der jeweiligen Rechteinhaber und unterliegen deren eigenen Lizenzbedingungen.</p><h2>Verbraucherstreitbeilegung</h2><p>Jamie Bevan ist nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen, soweit nicht im Einzelfall eine gesetzliche Verpflichtung besteht.</p></div></div></section></>;
}
