import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Imprint",
  description: "Operator, contact and copyright information for L4Gym.",
};

export default function Page() {
  return <><section className="page-hero"><div className="shell"><div><p className="eyebrow">Imprint</p><h1>Website operator information.</h1></div><p>Information provided for this commercial project operated from Germany.</p></div></section><section className="page-body"><div className="shell page-grid"><div><span className="number-tag">L4GYM / IMPRINT</span><h2>Jamie Bevan<br/>L4Gym</h2></div><div className="prose"><div className="legal-note"><strong>Information required before live launch</strong><p>The legally serviceable business address below has not yet been provided. This preview is therefore not a complete live-site imprint.</p></div><h2>Information pursuant to section 5 DDG</h2><p>Jamie Bevan<br/>L4Gym — software and commercial fitness technology project<br/><span className="legal-placeholder">[STREET AND HOUSE NUMBER REQUIRED]</span><br/><span className="legal-placeholder">[POSTCODE AND CITY REQUIRED]</span><br/>Germany</p><h2>Contact</h2><p>Email: <a href="mailto:jamie@l4gym.com">jamie@l4gym.com</a><br/>Website: <a href="https://www.l4gym.com">www.l4gym.com</a></p><p>No private telephone number is published on this website.</p><h2>Business status</h2><p>L4Gym is currently a software and commercial fitness technology project developed and operated by Jamie Bevan. It is not described on this website as a limited company, GmbH, Ltd, ehf or other incorporated entity.</p><h2>Editorial responsibility</h2><p>Responsible for content: Jamie Bevan<br/><span className="legal-placeholder">[SERVICEABLE ADDRESS REQUIRED]</span></p><h2>Copyright</h2><p><strong>Copyright © 2026 Jamie Bevan. All rights reserved.</strong></p><p>L4Gym software, original website content, documentation, graphics, interface designs and associated proprietary materials are protected by applicable intellectual-property laws. They may not be copied, reproduced, distributed, modified or commercially exploited without prior written permission, except where permitted by law or applicable third-party licences.</p><p>Third-party software, libraries, trademarks, images, fonts and other third-party materials remain the property of their respective owners and are subject to their own licence terms.</p><h2>Consumer dispute resolution</h2><p>Jamie Bevan is not willing or obliged to participate in dispute-resolution proceedings before a consumer arbitration board, unless a legal obligation applies in a specific case.</p></div></div></section></>;
}
